package com.example.moshidemo.gson.data2

import com.xxf.json.gson.booster.annotation.AutoGeneratedJsonAdapter
import com.example.moshidemo.gson.data.WrapperDTO2


@AutoGeneratedJsonAdapter
data class WrapperDTO4(val child: WrapperDTO2.Companion.Child2?=null) {
}