package com.example.moshidemo

import com.xxf.json.gson.booster.annotation.AutoGeneratedJsonAdapter

@AutoGeneratedJsonAdapter
class WrapperDTO(val child:Child= Child(1)) {
    @AutoGeneratedJsonAdapter
    class Child(val age:Int=1){

    }
}